---
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    helm.sh/weight: "0"
    opendatahub.io/accelerator-name: ''
    opendatahub.io/apiProtocol: REST
    opendatahub.io/template-display-name: vLLM
    opendatahub.io/template-name: vllm
    openshift.io/display-name: qwen3-8b
  name: qwen3-8b
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  builtInAdapter:
    modelLoadingTimeoutMillis: 90000
  containers:
    - args:
        - '--dtype=half'
        - '--gpu-memory-utilization=0.95'
        - '--enable-chunked-prefill'
        - '--port=8080'
        - '--model=/mnt/models'
        - '--served-model-name=qwen3-8b'
        - '--override-generation-config'
        - '{"enable_thinking": false}'
        - '--max-model-len'
        - '2048'
        - '--max-num-seqs'
        - '384'
        - '--max-num-batched-tokens'
        - '12288'
      env:
        - name: VLLM_CONFIG_ROOT
          value: /tmp
      image: 'quay.io/modh/vllm:rhoai-2.19-cuda'
      name: kserve-container
      ports:
        - containerPort: 8080
          name: http1
          protocol: TCP
      volumeMounts:
        - mountPath: /dev/shm
          name: shm
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: pytorch
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 2Gi
      name: shm
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    helm.sh/weight: "1"
    openshift.io/display-name: qwen3-8b
    serving.kserve.io/deploymentMode: RawDeployment
  name: qwen3-8b
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    automountServiceAccountToken: false
    maxReplicas: {{ .Values.replicas.llama }}
    minReplicas: {{ .Values.replicas.llama }}
    model:
      modelFormat:
        name: pytorch
      name: ''
      resources:
        limits:
          cpu: '4'
          memory: 24Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: '2'
          memory: 16Gi
          nvidia.com/gpu: '1'
      runtime: qwen3-8b
      storageUri: 'oci://quay.io/redhat-ai-services/modelcar-catalog:qwen3-8b'
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
